<?php
class EvaluationConstants
{
    public static $ratingTypesMap = [
        'GS402' => 'engagement',
        'GS404' => 'rating',
        'GS405' => 'organization',
        'GS406' => 'feedback',
        'GS407' => 'challenge',
        'GS408' => 'workload',
        'YC005' => 'workload',
        'YC006' => 'rating',
        'YC007' => 'major',
        'YC305' => 'workload',
        'YC306' => 'rating',
        'YC307' => 'major',
        'YC402' => 'engagement',
        'YC404' => 'rating',
        'YC405' => 'organization',
        'YC406' => 'feedback',
        'YC407' => 'challenge',
        'YC408' => 'workload',
        'YC402-YCWR' => 'engagement',
        'YC404-YCWR' => 'rating',
        'YC405-YCWR' => 'organization',
        'YC406-YCWR' => 'feedback',
        'YC407-YCWR' => 'challenge',
        'YC408-YCWR' => 'workload',
        'YC402-YXWR' => 'engagement',
        'YC404-YXWR' => 'rating',
        'YC405-YXWR' => 'organization',
        'YC406-YXWR' => 'feedback',
        'YC407-YXWR' => 'challenge',
        'YC408-YXWR' => 'workload',
        'PH001' => 'workload',
        'PH002' => 'rating',
        'PH003' => 'professor',
        'PH004' => 'sensitivity'
    ];

    public static $commentTypesMap = [
        'YC004' => 'summary',
        'GS003' => 'summary',
        'GS009' => 'knowledge',
        'YC304' => 'summary',
        'YC401' => 'knowledge',
        'YC403' => 'strengthsWeaknesses',
        'YC409' => 'recommend',
        'YC401-YCWR' => 'knowledge',
        'YC403-YCWR' => 'strengthsWeaknesses',
        'YC409-YCWR' => 'recommend',
        'YC401-YXWR' => 'knowledge',
        'YC403-YXWR' => 'strengthsWeaknesses',
        'YC409-YXWR' => 'recommend',
        'GS401' => 'knowledge',
        'GS403' => 'strengthsWeaknesses',
        'GS409' => 'recommend',
        'PH005' => 'hoursPerWeek',
        'PH006' => 'overall',
        'PH007' => 'overallProfessor',
        'PH008' => 'teachingAssistant',
        'PH009' => 'summary',
    ];
}
