import { expectType, TypeOf } from 'ts-expect';
import chroma from 'chroma-js';
import type { Listing } from '../utilities/common';

// Phrases for search speed [50 character limit]
export const searchSpeed = {
  fast: [
    'fast',
    'kinda fast',
    'not too slow',
    'you try loading this many courses',
    'not not not fast',
    'faster than Handsome Dan',
    'faster than the doors in HQ',
    'faster than the Silliman elevator',
    'faster than the HY ticket pick-up line',
    'faster than debugging binary bomb',
    'faster than October break',
    'faster than it takes to get to Murray',
  ],
  faster: [
    'faster',
    'really fast',
    'blazing fast',
    'faster than Zoom',
    'not not fast',
  ],
  fastest: [
    'fastest',
    'wicked fast',
    'faster than Usain',
    'faster than Yale One-Day-Breaks',
    'faster than drivers on Elm St',
    'faster than the speed of light',
    'faster than seniors when they see a gut',
    'faster than Higgins on paintball',
    'faster than YPopUp getting reserved',
    "faster than durfee's tenders selling out",
    'faster than sonic the hedgehog',
    'faster than an art-stem double major drops art',
    'faster than switching your major to CS',
    'faster than you can sell out to consulting',
    'faster than HAL',
    'faster than HY tickets selling out',
    'faster than YSO Halloween tickets selling out',
    'faster than the naked run',
  ],
};

export const sortbyOptions = [
  { label: 'Sort by Course Code', value: 'course_code', numeric: false },
  { label: 'Sort by Course Number', value: 'number', numeric: true },
  { label: 'Sort by Course Title', value: 'title', numeric: false },
  { label: 'Sort by Friends', value: 'friend', numeric: true },
  { label: 'Sort by Course Rating', value: 'average_rating', numeric: true },
  {
    label: 'Sort by Professor Rating',
    value: 'average_professor',
    numeric: true,
  },
  { label: 'Sort by Workload', value: 'average_workload', numeric: true },
  {
    label: 'Sort by Guts (Overall - Workload)',
    value: 'average_gut_rating',
    numeric: true,
  },
  { label: 'Sort by Last Enrollment', value: 'last_enrollment', numeric: true },
  { label: 'Sort by Days & Times', value: 'times_by_day', numeric: true },
] as const;

// Make sure we can only sort by keys in the listing, or by facebook.
export type SortKeys = keyof Listing | 'friend';
const _number = 0;
const _sortKeys = sortbyOptions[_number].value;
expectType<TypeOf<SortKeys, typeof _sortKeys>>(true);
export type SortByOption = (typeof sortbyOptions)[number];

export const areas = ['Hu', 'So', 'Sc'] as const;
export const skills = ['QR', 'WR', 'L1', 'L2', 'L3', 'L4', 'L5'] as const;
export type AreasType = (typeof areas)[number];
export type SkillsType = (typeof skills)[number];

export const skillsAreasColors: { [key: string]: string } = {
  Hu: '#9970AB',
  So: '#4393C3',
  Sc: '#5AAE61',
  QR: '#CC3311',
  WR: '#EC7014',
  L: '#000000',
  L1: '#888888',
  L2: '#888888',
  L3: '#888888',
  L4: '#888888',
  L5: '#888888',
};

export const skillsAreasOptions = [
  {
    label: 'Areas',
    options: [
      {
        label: 'Hu - Humanities & Arts',
        value: 'Hu',
        color: skillsAreasColors.Hu,
      },
      {
        label: 'So - Social Sciences',
        value: 'So',
        color: skillsAreasColors.So,
      },
      { label: 'Sc - Sciences', value: 'Sc', color: skillsAreasColors.Sc },
    ],
  },
  {
    label: 'Skills',
    options: [
      {
        label: 'QR - Quantitative Reasoning',
        value: 'QR',
        color: skillsAreasColors.QR,
      },
      { label: 'WR - Writing', value: 'WR', color: skillsAreasColors.WR },
      { label: 'L - All Language', value: 'L', color: skillsAreasColors.L },
      {
        label: 'L1 - Language Level 1',
        value: 'L1',
        color: skillsAreasColors.L1,
      },
      {
        label: 'L2 - Language Level 2',
        value: 'L2',
        color: skillsAreasColors.L2,
      },
      {
        label: 'L3 - Language Level 3',
        value: 'L3',
        color: skillsAreasColors.L3,
      },
      {
        label: 'L4 - Language Level 4',
        value: 'L4',
        color: skillsAreasColors.L4,
      },
      {
        label: 'L5 - Language Level 5',
        value: 'L5',
        color: skillsAreasColors.L5,
      },
    ],
  },
] as const;

export const ratingColormap = chroma
  .scale(['#f8696b', '#ffeb84', '#63b37b'])
  .domain([1, 5]);
export const workloadColormap = chroma
  .scale(['#63b37b', '#ffeb84', '#f8696b'])
  .domain([1, 5]);

// Maybe the number type is causing the error? (but it works fine on navbar search hmmm)
export const creditOptions = [
  { label: '0.5', value: 0.5 },
  { label: '1', value: 1 },
  { label: '1.5', value: 1.5 },
  { label: '2', value: 2 },
] as const;

export const courseInfoAttributesOptions = [
  { value: "DI: Area I", label: "DI: Area I" },
  { value: "DI: Area II", label: "DI: Area II" },
  { value: "DI: Area III", label: "DI: Area III" },
  { value: "DI: Area IV", label: "DI: Area IV" },
  { value: "DI: Area V", label: "DI: Area V" },
  { value: "DI: BRAD", label: "DI: BRAD" },
  { value: "DI: Diversity", label: "DI: Diversity" },
  { value: "DI: Ethics", label: "DI: Ethics" },
  { value: "DI: Hebrew Bible", label: "DI: Hebrew Bible" },
  { value: "DI: Homiletics", label: "DI: Homiletics" },
  { value: "DI: Latin(x) Am Christianity", label: "DI: Latin(x) Am Christianity" },
  { value: "DI: New Testament", label: "DI: New Testament" },
  { value: "DI: Non-Christian Religions", label: "DI: Non-Christian Religions" },
  { value: "DI: Theology", label: "DI: Theology" },
  { value: "DI: WGSS", label: "DI: WGSS" },
  { value: "GB: Core", label: "GB: Core" },
  { value: "GB: Cross-School Cross-Listed", label: "GB: Cross-School Cross-Listed" },
  { value: "GB: Elective", label: "GB: Elective" },
  { value: "GB: Half-Term Course (First)", label: "GB: Half-Term Course (First)" },
  { value: "GB: Half-Term Course (Second)", label: "GB: Half-Term Course (Second)" },
  { value: "GB: Prog. Eval. Cert.", label: "GB: Prog. Eval. Cert." },
  { value: "GB: SAT-UNSAT", label: "GB: SAT-UNSAT" },
  { value: "GB: Sub GLBL 5020", label: "GB: Sub GLBL 5020" },
  { value: "GS HIST: Ancient", label: "GS HIST: Ancient" },
  { value: "GS HIST: Early Modern", label: "GS HIST: Early Modern" },
  { value: "GS HIST: Medieval", label: "GS HIST: Medieval" },
  { value: "GS HIST: Modern", label: "GS HIST: Modern" },
  { value: "Hybrid; in-person & remote", label: "Hybrid; in-person & remote" },
  { value: "NU: Adult Gero Acute Care", label: "NU: Adult Gero Acute Care" },
  { value: "NU: Adult Gero Primary Care", label: "NU: Adult Gero Primary Care" },
  { value: "NU: DNP Clinical track", label: "NU: DNP Clinical track" },
  { value: "NU: DNP Leadership track", label: "NU: DNP Leadership track" },
  { value: "NU: Dual Spec, Midwifery WH", label: "NU: Dual Spec, Midwifery WH" },
  { value: "NU: Family Nurse Practitioner", label: "NU: Family Nurse Practitioner" },
  { value: "NU: GEPN, pre-spec in nursing", label: "NU: GEPN, pre-spec in nursing" },
  { value: "NU: Nurse Midwifery", label: "NU: Nurse Midwifery" },
  { value: "NU: Pediatric NP Acute Care", label: "NU: Pediatric NP Acute Care" },
  { value: "NU: Pediatric NP Primary Care", label: "NU: Pediatric NP Primary Care" },
  { value: "NU: Psych Mental Hlth Spec", label: "NU: Psych Mental Hlth Spec" },
  { value: "NU: Women's Health", label: "NU: Women's Health" },
  { value: "PH: Climate Change and Health", label: "PH: Climate Change and Health" },
  { value: "PH: Global Health, Biomedicine", label: "PH: Global Health, Biomedicine" },
  { value: "PH: Global Health, Development/Political Economy", label: "PH: Global Health, Development/Political Economy" },
  { value: "PH: Global Health, Epidemiology", label: "PH: Global Health, Epidemiology" },
  { value: "PH: Global Health, Ethics/Humanities/History", label: "PH: Global Health, Ethics/Humanities/History" },
  { value: "PH: Global Health, Implementation Science", label: "PH: Global Health, Implementation Science" },
  { value: "PH: Global Health, Psychosocial/Social and behavioral/Anthropology", label: "PH: Global Health, Psychosocial/Social and behavioral/Anthropology" },
  { value: "PH: Public Health Modeling", label: "PH: Public Health Modeling" },
  { value: "Taught in-person", label: "Taught in-person" },
  { value: "Taught remotely", label: "Taught remotely" },
  { value: "YC AMST: Cultural Hist/Studies", label: "YC AMST: Cultural Hist/Studies" },
  { value: "YC AMST: Early Americas", label: "YC AMST: Early Americas" },
  { value: "YC AMST: First-Year Sem", label: "YC AMST: First-Year Sem" },
  { value: "YC AMST: Gateway Courses", label: "YC AMST: Gateway Courses" },
  { value: "YC AMST: Junior Seminars", label: "YC AMST: Junior Seminars" },
  { value: "YC AMST: Senior Seminars", label: "YC AMST: Senior Seminars" },
  { value: "YC AMST: Special&Sr Projects", label: "YC AMST: Special&Sr Projects" },
  { value: "YC AMST: Survey of Am Lit", label: "YC AMST: Survey of Am Lit" },
  { value: "YC Anthropology: Archaeology", label: "YC Anthropology: Archaeology" },
  { value: "YC Anthropology: Biological", label: "YC Anthropology: Biological" },
  { value: "YC Anthropology: Linguistic", label: "YC Anthropology: Linguistic" },
  { value: "YC Anthropology: Sociocultural", label: "YC Anthropology: Sociocultural" },
  { value: "YC ARCG: Advanced Lab", label: "YC ARCG: Advanced Lab" },
  { value: "YC ARCG: Intro Survey", label: "YC ARCG: Intro Survey" },
  { value: "YC ARCG: Theory", label: "YC ARCG: Theory" },
  { value: "YC ARCH: History & Theory", label: "YC ARCH: History & Theory" },
  { value: "YC ARCH: Materials & Design", label: "YC ARCH: Materials & Design" },
  { value: "YC ARCH: Structures & Computation", label: "YC ARCH: Structures & Computation" },
  { value: "YC ARCH: Urbanism & Landscape", label: "YC ARCH: Urbanism & Landscape" },
  { value: "YC ASTR: Sci/Math Elective BA", label: "YC ASTR: Sci/Math Elective BA" },
  { value: "YC CHEM: Advanced Courses", label: "YC CHEM: Advanced Courses" },
  { value: "YC CHEM: GR of Interest to UG", label: "YC CHEM: GR of Interest to UG" },
  { value: "YC CHEM: Intermediate Courses", label: "YC CHEM: Intermediate Courses" },
  { value: "YC CHEM: Introductory Courses", label: "YC CHEM: Introductory Courses" },
  { value: "YC CHEM: Nonmajor w/o Prereq", label: "YC CHEM: Nonmajor w/o Prereq" },
  { value: "YC Climate Science: Anthropogenic", label: "YC Climate Science: Anthropogenic" },
  { value: "YC Climate Science: Basic", label: "YC Climate Science: Basic" },
  { value: "YC Climate Science: Elective", label: "YC Climate Science: Elective" },
  { value: "YC Climate Science: Solutions", label: "YC Climate Science: Solutions" },
  { value: "YC Climate: Sci/Eng/Tech", label: "YC Climate: Sci/Eng/Tech" },
  { value: "YC CLSS: Ancient Hist Greece", label: "YC CLSS: Ancient Hist Greece" },
  { value: "YC CLSS: Ancient Hist Rome", label: "YC CLSS: Ancient Hist Rome" },
  { value: "YC CLSS: Hist, Phil, Art, Arcg", label: "YC CLSS: Hist, Phil, Art, Arcg" },
  { value: "YC CLSS: Lit/Cult Anc Greece", label: "YC CLSS: Lit/Cult Anc Greece" },
  { value: "YC CLSS: Lit/Cult Anc Rome", label: "YC CLSS: Lit/Cult Anc Rome" },
  { value: "YC Cognitive Sci: Skills", label: "YC Cognitive Sci: Skills" },
  { value: "YC Courses Offered After Registration Closed", label: "YC Courses Offered After Registration Closed" },
  { value: "YC CPLI: Elective in CP & Ling", label: "YC CPLI: Elective in CP & Ling" },
  { value: "YC CPLT: 17th-18th centuries", label: "YC CPLT: 17th-18th centuries" },
  { value: "YC CPLT: Antiquity", label: "YC CPLT: Antiquity" },
  { value: "YC CPLT: Early Modern", label: "YC CPLT: Early Modern" },
  { value: "YC CPLT: FILM", label: "YC CPLT: FILM" },
  { value: "YC CPLT: Medieval", label: "YC CPLT: Medieval" },
  { value: "YC CPLT: the Modern period (1800–present)", label: "YC CPLT: the Modern period (1800–present)" },
  { value: "YC CPLT: Theory", label: "YC CPLT: Theory" },
  { value: "YC CPLT: Translation Studies", label: "YC CPLT: Translation Studies" },
  { value: "YC CPSC&MATH Adv CS Elective", label: "YC CPSC&MATH Adv CS Elective" },
  { value: "YC CPSC: Elective", label: "YC CPSC: Elective" },
  { value: "YC CSEC: Elective not CS or EC", label: "YC CSEC: Elective not CS or EC" },
  { value: "YC CSEC: Electv intrsctn CS/EC", label: "YC CSEC: Electv intrsctn CS/EC" },
  { value: "YC E&EB: BS Elective", label: "YC E&EB: BS Elective" },
  { value: "YC E&EB: Intermdiate/Advanced", label: "YC E&EB: Intermdiate/Advanced" },
  { value: "YC E&EB: Introductory Courses", label: "YC E&EB: Introductory Courses" },
  { value: "YC E&EB: Organismal Lec/Labs", label: "YC E&EB: Organismal Lec/Labs" },
  { value: "YC E&EB: Prereq Option", label: "YC E&EB: Prereq Option" },
  { value: "YC ECON: Core", label: "YC ECON: Core" },
  { value: "YC ECON: Development", label: "YC ECON: Development" },
  { value: "YC ECON: EconData", label: "YC ECON: EconData" },
  { value: "YC ECON: Education", label: "YC ECON: Education" },
  { value: "YC ECON: Environment", label: "YC ECON: Environment" },
  { value: "YC ECON: Finance", label: "YC ECON: Finance" },
  { value: "YC ECON: Health", label: "YC ECON: Health" },
  { value: "YC ECON: History", label: "YC ECON: History" },
  { value: "YC ECON: Industrial Organization", label: "YC ECON: Industrial Organization" },
  { value: "YC ECON: International Relations", label: "YC ECON: International Relations" },
  { value: "YC ECON: Introductory", label: "YC ECON: Introductory" },
  { value: "YC ECON: Labor", label: "YC ECON: Labor" },
  { value: "YC ECON: Law", label: "YC ECON: Law" },
  { value: "YC ECON: Macroeconomics", label: "YC ECON: Macroeconomics" },
  { value: "YC ECON: Methodology", label: "YC ECON: Methodology" },
  { value: "YC ECON: Microtheory", label: "YC ECON: Microtheory" },
  { value: "YC ECON: Neuro", label: "YC ECON: Neuro" },
  { value: "YC ECON: Political Economy", label: "YC ECON: Political Economy" },
  { value: "YC ECON: Poverty", label: "YC ECON: Poverty" },
  { value: "YC ECON: Public", label: "YC ECON: Public" },
  { value: "YC EDST: Indv Society", label: "YC EDST: Indv Society" },
  { value: "YC EDST: Social Context", label: "YC EDST: Social Context" },
  { value: "YC English: 18th/19th Century", label: "YC English: 18th/19th Century" },
  { value: "YC English: 20th/21st Century", label: "YC English: 20th/21st Century" },
  { value: "YC English: Creative Writing", label: "YC English: Creative Writing" },
  { value: "YC English: Junior Seminar", label: "YC English: Junior Seminar" },
  { value: "YC English: Medieval", label: "YC English: Medieval" },
  { value: "YC English: Renaissance", label: "YC English: Renaissance" },
  { value: "YC English: Senior Seminar", label: "YC English: Senior Seminar" },
  { value: "YC ENRG: Energy & Environment", label: "YC ENRG: Energy & Environment" },
  { value: "YC ENRG: Energy & Society", label: "YC ENRG: Energy & Society" },
  { value: "YC ENRG: Energy Science & Tech", label: "YC ENRG: Energy Science & Tech" },
  { value: "YC EP&E Economics Core", label: "YC EP&E Economics Core" },
  { value: "YC EP&E Ethics Core", label: "YC EP&E Ethics Core" },
  { value: "YC EP&E Intro Econometrics", label: "YC EP&E Intro Econometrics" },
  { value: "YC EP&E Intro Game Theory", label: "YC EP&E Intro Game Theory" },
  { value: "YC EP&E Intro Microeconomics", label: "YC EP&E Intro Microeconomics" },
  { value: "YC EP&E Politics Core", label: "YC EP&E Politics Core" },
  { value: "YC EP&E: Advanced Seminar", label: "YC EP&E: Advanced Seminar" },
  { value: "YC EP&E: Intro Ethics", label: "YC EP&E: Intro Ethics" },
  { value: "YC EP&E: Intro Political Phil", label: "YC EP&E: Intro Political Phil" },
  { value: "YC ER&M: Elect within the Major", label: "YC ER&M: Elect within the Major" },
  { value: "YC ER&M: Methods Course", label: "YC ER&M: Methods Course" },
  { value: "YC ER&M: Required Courses", label: "YC ER&M: Required Courses" },
  { value: "YC ER&M: Research & Sr Essay", label: "YC ER&M: Research & Sr Essay" },
  { value: "YC Ethnography: Elective", label: "YC Ethnography: Elective" },
  { value: "YC Ethnography: Methods", label: "YC Ethnography: Methods" },
  { value: "YC EVST B.S. NatSci Lab", label: "YC EVST B.S. NatSci Lab" },
  { value: "YC EVST: Advanced Seminar", label: "YC EVST: Advanced Seminar" },
  { value: "YC EVST: Core BA Natural Scie", label: "YC EVST: Core BA Natural Scie" },
  { value: "YC EVST: Core BS Natural Scie", label: "YC EVST: Core BS Natural Scie" },
  { value: "YC EVST: Core Human/Social Sci", label: "YC EVST: Core Human/Social Sci" },
  { value: "YC FILM: Critical Studies", label: "YC FILM: Critical Studies" },
  { value: "YC FILM: Production", label: "YC FILM: Production" },
  { value: "YC FILM: World Cinema", label: "YC FILM: World Cinema" },
  { value: "YC FREN: Pre-1800", label: "YC FREN: Pre-1800" },
  { value: "YC FREN: Taught in English", label: "YC FREN: Taught in English" },
  { value: "YC FREN: Taught in French", label: "YC FREN: Taught in French" },
  { value: "YC GLBL: 121 Alternative Crse", label: "YC GLBL: 121 Alternative Crse" },
  { value: "YC GLBL: Addtl Methods Course", label: "YC GLBL: Addtl Methods Course" },
  { value: "YC GLBL: Elective", label: "YC GLBL: Elective" },
  { value: "YC GLHTH: Bio & Env Influences", label: "YC GLHTH: Bio & Env Influences" },
  { value: "YC GLHTH: Health & Societies", label: "YC GLHTH: Health & Societies" },
  { value: "YC GLHTH: Hist Approaches", label: "YC GLHTH: Hist Approaches" },
  { value: "YC GLHTH: Perf, Rep & Health", label: "YC GLHTH: Perf, Rep & Health" },
  { value: "YC GLHTH: Polit Econ & Govern", label: "YC GLHTH: Polit Econ & Govern" },
  { value: "YC GLHTH: Quantitative Data", label: "YC GLHTH: Quantitative Data" },
  { value: "YC GMAN: Aesthetics & Arts", label: "YC GMAN: Aesthetics & Arts" },
  { value: "YC GMAN: Critical Thought", label: "YC GMAN: Critical Thought" },
  { value: "YC GMAN: History & Politics", label: "YC GMAN: History & Politics" },
  { value: "YC GMAN: Literature", label: "YC GMAN: Literature" },
  { value: "YC GMAN: Media & Media Theory", label: "YC GMAN: Media & Media Theory" },
  { value: "YC HIST: Africa", label: "YC HIST: Africa" },
  { value: "YC HIST: Asia", label: "YC HIST: Asia" },
  { value: "YC HIST: Cultural History", label: "YC HIST: Cultural History" },
  { value: "YC HIST: Departmental Seminars", label: "YC HIST: Departmental Seminars" },
  { value: "YC HIST: Empires & Colonialism", label: "YC HIST: Empires & Colonialism" },
  { value: "YC HIST: Environmental History", label: "YC HIST: Environmental History" },
  { value: "YC HIST: Europe", label: "YC HIST: Europe" },
  { value: "YC HIST: First-Year Seminars", label: "YC HIST: First-Year Seminars" },
  { value: "YC HIST: Ideas & Intellectuals", label: "YC HIST: Ideas & Intellectuals" },
  { value: "YC HIST: Intl & Diplomat Hist", label: "YC HIST: Intl & Diplomat Hist" },
  { value: "YC HIST: Latin America", label: "YC HIST: Latin America" },
  { value: "YC HIST: Lecture Courses", label: "YC HIST: Lecture Courses" },
  { value: "YC HIST: Middle East", label: "YC HIST: Middle East" },
  { value: "YC HIST: Pltcs, Law & Govt", label: "YC HIST: Pltcs, Law & Govt" },
  { value: "YC HIST: Race Gender & Sexuality", label: "YC HIST: Race Gender & Sexuality" },
  { value: "YC HIST: Religion in Context", label: "YC HIST: Religion in Context" },
  { value: "YC HIST: Sci, Tech, & Medicine", label: "YC HIST: Sci, Tech, & Medicine" },
  { value: "YC HIST: Senior Essay", label: "YC HIST: Senior Essay" },
  { value: "YC HIST: Soc Chng & Social MVMN", label: "YC HIST: Soc Chng & Social MVMN" },
  { value: "YC HIST: The World Economy", label: "YC HIST: The World Economy" },
  { value: "YC HIST: United States", label: "YC HIST: United States" },
  { value: "YC HIST: War & Society", label: "YC HIST: War & Society" },
  { value: "YC HIST: World", label: "YC HIST: World" },
  { value: "YC HIST: Writing Tutorial", label: "YC HIST: Writing Tutorial" },
  { value: "YC HistofArt: 1500-1800", label: "YC HistofArt: 1500-1800" },
  { value: "YC HistofArt: 800-1500", label: "YC HistofArt: 800-1500" },
  { value: "YC HistofArt: Africa & Pacific", label: "YC HistofArt: Africa & Pacific" },
  { value: "YC HistofArt: Asia/Near East", label: "YC HistofArt: Asia/Near East" },
  { value: "YC HistofArt: Europe", label: "YC HistofArt: Europe" },
  { value: "YC HistofArt: Post-1800", label: "YC HistofArt: Post-1800" },
  { value: "YC HistofArt: Pre-800", label: "YC HistofArt: Pre-800" },
  { value: "YC HistofArt: The Americas", label: "YC HistofArt: The Americas" },
  { value: "YC HistofArt: Transchron", label: "YC HistofArt: Transchron" },
  { value: "YC HistofArt: Transregional", label: "YC HistofArt: Transregional" },
  { value: "YC History: Preindustrial", label: "YC History: Preindustrial" },
  { value: "YC HSHM: Colonial Know & Power", label: "YC HSHM: Colonial Know & Power" },
  { value: "YC HSHM: Environ & Society", label: "YC HSHM: Environ & Society" },
  { value: "YC HSHM: Gender, Reprod and Body", label: "YC HSHM: Gender, Reprod and Body" },
  { value: "YC HSHM: Global Health", label: "YC HSHM: Global Health" },
  { value: "YC HSHM: Med & Public Health", label: "YC HSHM: Med & Public Health" },
  { value: "YC HSHM: Media Info & Public", label: "YC HSHM: Media Info & Public" },
  { value: "YC HSHM: Minds and Brains", label: "YC HSHM: Minds and Brains" },
  { value: "YC HSHM: Sci, Tech & Society", label: "YC HSHM: Sci, Tech & Society" },
  { value: "YC HUMS: Interpretations", label: "YC HUMS: Interpretations" },
  { value: "YC HUMS: Modernities", label: "YC HUMS: Modernities" },
  { value: "YC ISLM: Islamic Art, Arch, Lit", label: "YC ISLM: Islamic Art, Arch, Lit" },
  { value: "YC ISLM: Islamic History", label: "YC ISLM: Islamic History" },
  { value: "YC ISLM: Islamic Religion", label: "YC ISLM: Islamic Religion" },
  { value: "YC ISLM: Islamic Society", label: "YC ISLM: Islamic Society" },
  { value: "YC ITAL: Taught in English", label: "YC ITAL: Taught in English" },
  { value: "YC ITAL: Taught in Italian", label: "YC ITAL: Taught in Italian" },
  { value: "YC LING Brdth: Comp Ling", label: "YC LING Brdth: Comp Ling" },
  { value: "YC LING Brdth: Historical Ling", label: "YC LING Brdth: Historical Ling" },
  { value: "YC LING Brdth: Lang&Mind/Brain", label: "YC LING Brdth: Lang&Mind/Brain" },
  { value: "YC LING Brdth: Semntcs/Pragmat", label: "YC LING Brdth: Semntcs/Pragmat" },
  { value: "YC LING Breadth: Morphology", label: "YC LING Breadth: Morphology" },
  { value: "YC LING Breadth: Phonetics", label: "YC LING Breadth: Phonetics" },
  { value: "YC LING Depth: Comp Linguistic", label: "YC LING Depth: Comp Linguistic" },
  { value: "YC LING Depth: Historical Ling", label: "YC LING Depth: Historical Ling" },
  { value: "YC LING Depth: Lang&Mind/Brain", label: "YC LING Depth: Lang&Mind/Brain" },
  { value: "YC LING Depth: Morphology", label: "YC LING Depth: Morphology" },
  { value: "YC LING Depth: Phonetics", label: "YC LING Depth: Phonetics" },
  { value: "YC LING Depth: Phonology", label: "YC LING Depth: Phonology" },
  { value: "YC LING Depth: Semntcs/Pragmat", label: "YC LING Depth: Semntcs/Pragmat" },
  { value: "YC LING Depth: Syntax", label: "YC LING Depth: Syntax" },
  { value: "YC LING: Adv Courses/Seminars", label: "YC LING: Adv Courses/Seminars" },
  { value: "YC LING: American Sign Courses", label: "YC LING: American Sign Courses" },
  { value: "YC LING: Breadth", label: "YC LING: Breadth" },
  { value: "YC LING: Depth", label: "YC LING: Depth" },
  { value: "YC LING: Elective", label: "YC LING: Elective" },
  { value: "YC LING: Intermediate Courses", label: "YC LING: Intermediate Courses" },
  { value: "YC LING: Introductory Courses", label: "YC LING: Introductory Courses" },
  { value: "YC LING: Res Courses/Sr Essay", label: "YC LING: Res Courses/Sr Essay" },
  { value: "YC MA&PHL: add crse w/log comp", label: "YC MA&PHL: add crse w/log comp" },
  { value: "YC Math: Algebra/Number Theory", label: "YC Math: Algebra/Number Theory" },
  { value: "YC Math: Core Complex Analysis", label: "YC Math: Core Complex Analysis" },
  { value: "YC Math: Core Real Analysis", label: "YC Math: Core Real Analysis" },
  { value: "YC Math: Geometry/Topology", label: "YC Math: Geometry/Topology" },
  { value: "YC Math: Logic/Foundations", label: "YC Math: Logic/Foundations" },
  { value: "YC Math: Stat/Applied Math", label: "YC Math: Stat/Applied Math" },
  { value: "YC Mathematics: Analysis", label: "YC Mathematics: Analysis" },
  { value: "YC Mathematics: Core Algebra", label: "YC Mathematics: Core Algebra" },
  { value: "YC MDVL: East & SE Asia", label: "YC MDVL: East & SE Asia" },
  { value: "YC MDVL: Eur Russ & N Atlantic", label: "YC MDVL: Eur Russ & N Atlantic" },
  { value: "YC MDVL: Nr East & N Africa", label: "YC MDVL: Nr East & N Africa" },
  { value: "YC MDVL: S & Central Asia", label: "YC MDVL: S & Central Asia" },
  { value: "YC MENG: BS Technical Elective", label: "YC MENG: BS Technical Elective" },
  { value: "YC MENG: Eng Sci-Mech Crse", label: "YC MENG: Eng Sci-Mech Crse" },
  { value: "YC MMES Survey Course", label: "YC MMES Survey Course" },
  { value: "YC MMES: Adv Seminar", label: "YC MMES: Adv Seminar" },
  { value: "YC MMES: Distribution Crse", label: "YC MMES: Distribution Crse" },
  { value: "YC Music: Advanced Grp I", label: "YC Music: Advanced Grp I" },
  { value: "YC Music: Advanced Grp III", label: "YC Music: Advanced Grp III" },
  { value: "YC Music: Advanced Grp IV", label: "YC Music: Advanced Grp IV" },
  { value: "YC Music: Intermediate Grp I", label: "YC Music: Intermediate Grp I" },
  { value: "YC Music: Intermediate Grp II", label: "YC Music: Intermediate Grp II" },
  { value: "YC Music: Intermediate Grp III", label: "YC Music: Intermediate Grp III" },
  { value: "YC Music: Intermediate Grp IV", label: "YC Music: Intermediate Grp IV" },
  { value: "YC NELC: Foundations Course", label: "YC NELC: Foundations Course" },
  { value: "YC Not Taught In Target Language", label: "YC Not Taught In Target Language" },
  { value: "YC NSCI: Basic Allied Core", label: "YC NSCI: Basic Allied Core" },
  { value: "YC NSCI: Computational", label: "YC NSCI: Computational" },
  { value: "YC NSCI: Molecular/Cell/Biol", label: "YC NSCI: Molecular/Cell/Biol" },
  { value: "YC NSCI: Neuroscience Lab", label: "YC NSCI: Neuroscience Lab" },
  { value: "YC NSCI: Other Allied", label: "YC NSCI: Other Allied" },
  { value: "YC NSCI: Quantitative", label: "YC NSCI: Quantitative" },
  { value: "YC NSCI: Statistics Prereq", label: "YC NSCI: Statistics Prereq" },
  { value: "YC NSCI: Systems/Circuit/Behav", label: "YC NSCI: Systems/Circuit/Behav" },
  { value: "YC Phil: Ethics & Value Theory", label: "YC Phil: Ethics & Value Theory" },
  { value: "YC Phil: History of Philosophy", label: "YC Phil: History of Philosophy" },
  { value: "YC Phil: Intersctn PSYC/PHIL", label: "YC Phil: Intersctn PSYC/PHIL" },
  { value: "YC Phil: Logic", label: "YC Phil: Logic" },
  { value: "YC Phil: Metaphysics & Epistemol", label: "YC Phil: Metaphysics & Epistemol" },
  { value: "YC PLSC: American Govt", label: "YC PLSC: American Govt" },
  { value: "YC PLSC: Analyt Pol Theory", label: "YC PLSC: Analyt Pol Theory" },
  { value: "YC PLSC: Comparative Govt", label: "YC PLSC: Comparative Govt" },
  { value: "YC PLSC: Core Lecture", label: "YC PLSC: Core Lecture" },
  { value: "YC PLSC: Intnatl Relations", label: "YC PLSC: Intnatl Relations" },
  { value: "YC PLSC: Intro Courses", label: "YC PLSC: Intro Courses" },
  { value: "YC PLSC: Method & Formal Theory", label: "YC PLSC: Method & Formal Theory" },
  { value: "YC PLSC: Political Phil", label: "YC PLSC: Political Phil" },
  { value: "YC PLSC: Sr Essay/Dir Read", label: "YC PLSC: Sr Essay/Dir Read" },
  { value: "YC Prog: Advanced Programming", label: "YC Prog: Advanced Programming" },
  { value: "YC Prog: Applctions/Algorithms", label: "YC Prog: Applctions/Algorithms" },
  { value: "YC Prog: Data Structures", label: "YC Prog: Data Structures" },
  { value: "YC Prog: Programming", label: "YC Prog: Programming" },
  { value: "YC Prog: Programming Elective", label: "YC Prog: Programming Elective" },
  { value: "YC PSYC: Natural Science", label: "YC PSYC: Natural Science" },
  { value: "YC PSYC: Natural Science Core", label: "YC PSYC: Natural Science Core" },
  { value: "YC PSYC: NSCI Track Adv Scie", label: "YC PSYC: NSCI Track Adv Scie" },
  { value: "YC PSYC: NSCI Track RsrchMthds", label: "YC PSYC: NSCI Track RsrchMthds" },
  { value: "YC PSYC: NSCI Track Senior Sem", label: "YC PSYC: NSCI Track Senior Sem" },
  { value: "YC PSYC: Social Science", label: "YC PSYC: Social Science" },
  { value: "YC PSYC: Social Science Core", label: "YC PSYC: Social Science Core" },
  { value: "YC S&DS: Data Analy Disc Area", label: "YC S&DS: Data Analy Disc Area" },
  { value: "YC S&DS: Methods Data Science", label: "YC S&DS: Methods Data Science" },
  { value: "YC SAST: Premodern South Asia", label: "YC SAST: Premodern South Asia" },
  { value: "YC Sociology: Methods Course", label: "YC Sociology: Methods Course" },
  { value: "YC SOCY: Economic Sociology", label: "YC SOCY: Economic Sociology" },
  { value: "YC Sophomore Seminar", label: "YC Sophomore Seminar" },
  { value: "YC Urban Studies: Elective", label: "YC Urban Studies: Elective" },
  { value: "YC Urban Studies: Methods Crse", label: "YC Urban Studies: Methods Crse" },
  { value: "YC Urban Studies: Survey Crse", label: "YC Urban Studies: Survey Crse" },
  { value: "YC Urban Studies: Urban Lab", label: "YC Urban Studies: Urban Lab" },
  { value: "YC: Persia & Iran Content", label: "YC: Persia & Iran Content" },
  { value: "YC: Preference Selection Req'd", label: "YC: Preference Selection Req'd" },
  { value: "YC: THST Artistic Practice", label: "YC: THST Artistic Practice" },
  { value: "YC: THST Dramlit/ThHist/PerfTh", label: "YC: THST Dramlit/ThHist/PerfTh" },
  { value: "YC: THST Elective", label: "YC: THST Elective" },
  { value: "YC: THST Histories", label: "YC: THST Histories" },
  { value: "YC: THST Interarts", label: "YC: THST Interarts" },
  { value: "YC: THST non-English Dram Lit", label: "YC: THST non-English Dram Lit" },
  { value: "YC: THST Performance Theory", label: "YC: THST Performance Theory" },
  { value: "Writing Skill (Opt.)", label: "Writing Skill (Opt.)" },
  { value: "YC Music: Advanced Grp II", label: "YC Music: Advanced Grp II" },
] as const;

export const dayOptions = [
  { label: 'Monday', value: 'Monday' },
  { label: 'Tuesday', value: 'Tuesday' },
  { label: 'Wednesday', value: 'Wednesday' },
  { label: 'Thursday', value: 'Thursday' },
  { label: 'Friday', value: 'Friday' },
] as const;

// to get a list of abbreviations, run
// a distinct_on:school query over computed_course_info

// school labels were filled in manually
export const schoolOptions = [
  { label: 'Yale College', value: 'YC' },
  { label: 'School of Architecture', value: 'AC' },
  { label: 'School of Fine Arts', value: 'AT' },
  { label: 'Graduate School of Arts and Sciences', value: 'GS' },
  { label: 'Divinity School', value: 'DI' },
  { label: 'School of Drama', value: 'DR' },
  { label: 'School of the Environment', value: 'FS' },
  { label: 'Law School', value: 'LW' },
  { label: 'School of Medicine', value: 'MD' },
  { label: 'School of Management', value: 'MG' },
  { label: 'School of Music', value: 'MU' },
  { label: 'School of Nursing', value: 'NR' },
  { label: 'Physician Associate Program', value: 'PA' },
  { label: 'School of Public Health', value: 'PH' },
  { label: 'Summer Session', value: 'SU' },
] as const;

export const questions = [
  'assessment',
  'workload',
  'major',
  'engagement',
  'organized',
  'feedback',
  'challenge',
] as const;
export const question_text = {
  assessment: 'What is your overall assessment of this course?',
  workload:
    'Relative to other courses you have taken at Yale, the workload of this course was:',
  major:
    'Do you expect to use this class for credit toward your major, or toward a pre-professional program?',
  engagement: 'Your level of engagement with the course was:',
  organized: 'The course was well organized to facilitate student learning.',
  feedback: 'I received clear feedback that improved my learning.',
  challenge:
    'Relative to other courses you have taken at Yale, the level of intellectual challenge of this course was:',
} as const;
export const graph_labels = {
  assessment: ['poor', 'fair', 'good', 'very good', 'excellent'],
  workload: ['much less', 'less', 'same', 'greater', 'much greater'],
  engagement: ['very low', 'low', 'medium', 'high', 'very high'],
  organized: [
    'strongly disagree',
    'disagree',
    'neutral',
    'agree',
    'strongly agree',
  ],
  feedback: [
    'strongly disagree',
    'disagree',
    'neutral',
    'agree',
    'strongly agree',
  ],
  challenge: ['much less', 'less', 'same', 'greater', 'much greater'],
  major: [],
} as const;
export const graph_titles = {
  assessment: 'Overall',
  workload: 'Workload',
  engagement: 'Engagement',
  organized: 'Organization',
  feedback: 'Feedback Clarity',
  challenge: 'Intellectual Challenge',
  major: 'Taking for Major?',
} as const;

export const subjectOptions = [
  { value: 'ACCT', label: 'ACCT - Accounting' },
  { value: 'ADSC', label: 'ADSC - Administrative Sciences' },
  { value: 'AFAM', label: 'AFAM - African American Studies' },
  { value: 'AFAS', label: 'AFAS - African & African-Amer Studies' },
  { value: 'AFKN', label: 'AFKN - Afrikaans' },
  { value: 'AFST', label: 'AFST - African Studies' },
  { value: 'AKKD', label: 'AKKD - Akkadian' },
  { value: 'AMST', label: 'AMST - American Studies' },
  { value: 'AMTH', label: 'AMTH - Applied Mathematics' },
  { value: 'ANES', label: 'ANES - Anesthesiology' },
  { value: 'ANTH', label: 'ANTH - Anthropology' },
  { value: 'APHY', label: 'APHY - Applied Physics' },
  { value: 'ARBC', label: 'ARBC - Arabic' },
  { value: 'ARCG', label: 'ARCG - Archaeological Studies' },
  { value: 'ARCH', label: 'ARCH - Architecture' },
  { value: 'ARMN', label: 'ARMN - Armenian' },
  { value: 'ART', label: 'ART - Art' },
  { value: 'ASL', label: 'ASL - American Sign Language' },
  { value: 'ASTR', label: 'ASTR - Astronomy' },
  { value: 'B&BS', label: 'B&BS - Biological & Biomedical Sci' },
  { value: 'BENG', label: 'BENG - Biomedical Engineering' },
  { value: 'BIOL', label: 'BIOL - Biology' },
  { value: 'BIS', label: 'BIS - Biostatistics' },
  { value: 'BME', label: 'BME - Biomedical Engineering' },
  { value: 'BNGL', label: 'BNGL - Bengali' },
  { value: 'BRST', label: 'BRST - British Studies' },
  { value: 'BURM', label: 'BURM - Burmese' },
  { value: 'C&MP', label: 'C&MP - Cell & Molecular Physiology' },
  { value: 'CAND', label: 'CAND - Prep for Adv to Candidacy' },
  { value: 'CB&B', label: 'CB&B - Comp Biol & Bioinfomatics' },
  { value: 'CBIO', label: 'CBIO - Cell Biology' },
  { value: 'CDE', label: 'CDE - Chronic Disease Epidemiology' },
  { value: 'CENG', label: 'CENG - Chemical Engineering' },
  { value: 'CGSC', label: 'CGSC - Cognitive Science' },
  { value: 'CHEM', label: 'CHEM - Chemistry' },
  { value: 'CHLD', label: 'CHLD - Child Study' },
  { value: 'CHNS', label: 'CHNS - Chinese' },
  { value: 'CLCV', label: 'CLCV - Classical Civilization' },
  { value: 'CLSS', label: 'CLSS - Classics' },
  { value: 'CPAR', label: 'CPAR - Computing and the Arts' },
  { value: 'CPLT', label: 'CPLT - Comparative Literature' },
  { value: 'CPMD', label: 'CPMD - Comparative Medicine' },
  { value: 'CPSC', label: 'CPSC - Computer Science' },
  { value: 'CPTC', label: 'CPTC - Coptic' },
  { value: 'CSBF', label: 'CSBF - Coll Sem:Ben Franklin Coll' },
  { value: 'CSBK', label: 'CSBK - Coll Sem:Berkeley Coll' },
  { value: 'CSBR', label: 'CSBR - Coll Sem:Branford Coll' },
  { value: 'CSCC', label: 'CSCC - Coll Sem:Calhoun Coll' },
  { value: 'CSDC', label: 'CSDC - Coll Sem:Davenport Coll' },
  { value: 'CSEC', label: 'CSEC - Computer Science and Economics' },
  { value: 'CSES', label: 'CSES - Coll Sem:Ezra Stiles Coll' },
  { value: 'CSGH', label: 'CSGH - Coll Sem:Grace Hopper Coll' },
  { value: 'CSJE', label: 'CSJE - Coll Sem:Jonathan Edwards Coll' },
  { value: 'CSMC', label: 'CSMC - Coll Sem:Morse Coll' },
  { value: 'CSMY', label: 'CSMY - Coll Sem:Pauli Murray Coll' },
  { value: 'CSPC', label: 'CSPC - Coll Sem:Pierson Coll' },
  { value: 'CSSM', label: 'CSSM - Coll Sem:Silliman Coll' },
  { value: 'CSSY', label: 'CSSY - Coll Sem:Saybrook Coll' },
  { value: 'CSTC', label: 'CSTC - Coll Sem:Trumbull Coll' },
  { value: 'CSTD', label: 'CSTD - Coll Sem:Timothy Dwight Coll' },
  { value: 'CSYC', label: 'CSYC - Coll Sem: Yale Coll' },
  { value: 'CTLN', label: 'CTLN - Catalan' },
  { value: 'CZEC', label: 'CZEC - Czech' },
  { value: 'DERM', label: 'DERM - Dermatology' },
  { value: 'DEVN', label: 'DEVN - The DeVane Lecture Course' },
  { value: 'DIAG', label: 'DIAG - Diagnostic Radiology' },
  { value: 'DIR', label: 'DIR - DIrecting' },
  { value: 'DISA', label: 'DISA - Diss Research' },
  { value: 'DISR', label: 'DISR - Diss Research' },
  { value: 'DRAM', label: 'DRAM - Drama' },
  { value: 'DRST', label: 'DRST - Directed Studies' },
  { value: 'DUTC', label: 'DUTC - Dutch' },
  { value: 'E&EB', label: 'E&EB - Ecology & Evolutionary Biology' },
  { value: 'E&RS', label: 'E&RS - European & Russian Studies' },
  { value: 'EALL', label: 'EALL - East Asian Lang and Lit' },
  { value: 'EAST', label: 'EAST - East Asian Studies' },
  { value: 'ECON', label: 'ECON - Economics' },
  { value: 'EDST', label: 'EDST - Education Studies' },
  { value: 'EECS', label: 'EECS - Elec Eng & Comp Sci' },
  { value: 'EENG', label: 'EENG - Electrical Engineering' },
  { value: 'EGYP', label: 'EGYP - Egyptology' },
  { value: 'EHS', label: 'EHS - Environmental Health Sciences' },
  { value: 'EID', label: 'EID - Epidemiology Infectious Diseas' },
  { value: 'ELP', label: 'ELP - English Language Program' },
  { value: 'EMD', label: 'EMD - Epidemiology Microbial Disease' },
  { value: 'ENAS', label: 'ENAS - Engineering & Applied Science' },
  { value: 'ENGL', label: 'ENGL - English' },
  { value: 'ENHS', label: 'ENHS - Environmental Health Sciences' },
  { value: 'ENRG', label: 'ENRG - Energy Studies' },
  { value: 'ENV', label: 'ENV - Environment' },
  { value: 'ENVE', label: 'ENVE - Environmental Engineering' },
  { value: 'EP&E', label: 'EP&E - Ethics, Politics, & Economics' },
  { value: 'EPH', label: 'EPH - Epidemiology & Public Health' },
  { value: 'EPS', label: 'EPS - Earth and Planetary Sciences' },
  { value: 'ER&M', label: 'ER&M - Ethnicity, Race, & Migration' },
  { value: 'EVST', label: 'EVST - Environmental Studies' },
  { value: 'EXPA', label: 'EXPA - Experimental Pathology' },
  { value: 'F&ES', label: 'F&ES - Forestry & Environment Studies' },
  { value: 'FILM', label: 'FILM - Film & Media Studies' },
  { value: 'FNSH', label: 'FNSH - Finnish' },
  { value: 'FREN', label: 'FREN - French' },
  { value: 'G&G', label: 'G&G - Geology and Geophysics' },
  { value: 'GENE', label: 'GENE - Genetics' },
  { value: 'GHD', label: 'GHD - Global Health' },
  { value: 'GLBL', label: 'GLBL - Global Affairs' },
  { value: 'GMAN', label: 'GMAN - German' },
  { value: 'GMIC', label: 'GMIC - Germanic' },
  { value: 'GMST', label: 'GMST - German Studies' },
  { value: 'GRAN', label: 'GRAN - Gross Anatomy' },
  { value: 'GREK', label: 'GREK - Ancient Greek' },
  { value: 'GSAS', label: 'GSAS - Graduate School' },
  { value: 'HAUS', label: 'HAUS - Hausa' },
  { value: 'HEBR', label: 'HEBR - Modern Hebrew' },
  { value: 'HGRN', label: 'HGRN - Hungarian' },
  { value: 'HIST', label: 'HIST - History' },
  { value: 'HLTH', label: 'HLTH - Health Studies' },
  { value: 'HM&S', label: 'HM&S - History of Medicine & Science' },
  { value: 'HMRT', label: 'HMRT - Human Rights' },
  { value: 'HNDI', label: 'HNDI - Hindi' },
  { value: 'HPA', label: 'HPA - Health Policy Administration' },
  { value: 'HPM', label: 'HPM - Health Policy and Management' },
  { value: 'HPR', label: 'HPR - Health Policy Resources & Adm' },
  { value: 'HSAR', label: 'HSAR - History of Art' },
  { value: 'HSHM', label: 'HSHM - Hist of Science, Hist of Med' },
  { value: 'HSMD', label: 'HSMD - History of Medicine' },
  { value: 'HSPL', label: 'HSPL - History & Politics' },
  { value: 'HUMS', label: 'HUMS - Humanities' },
  { value: 'IBIO', label: 'IBIO - Immunobiology' },
  { value: 'IHD', label: 'IHD - International Health' },
  { value: 'IMED', label: 'IMED - Investigative Medicine' },
  { value: 'IND', label: 'IND - IndoEuropean' },
  { value: 'INDC', label: 'INDC - Indic' },
  { value: 'INDN', label: 'INDN - Indonesian' },
  { value: 'INMD', label: 'INMD - Internal Medicine' },
  { value: 'INP', label: 'INP - Interdpt Neuroscience Pgm' },
  { value: 'INRL', label: 'INRL - International Relations' },
  { value: 'INTL', label: 'INTL - International' },
  { value: 'INTS', label: 'INTS - International Studies' },
  { value: 'IRAN', label: 'IRAN - Iranian' },
  { value: 'IRES', label: 'IRES - Independent Research' },
  { value: 'ITAL', label: 'ITAL - Italian' },
  { value: 'JAPN', label: 'JAPN - Japanese' },
  { value: 'JDST', label: 'JDST - Judaic Studies' },
  { value: 'KHMR', label: 'KHMR - Khmer' },
  { value: 'KREN', label: 'KREN - Korean' },
  { value: 'LAST', label: 'LAST - Latin American Studies' },
  { value: 'LATN', label: 'LATN - Latin' },
  { value: 'LAW', label: 'LAW - Law' },
  { value: 'LBMD', label: 'LBMD - Laboratory Medicine' },
  { value: 'LING', label: 'LING - Linguistics' },
  { value: 'LITR', label: 'LITR - Literature' },
  { value: 'LUCE', label: 'LUCE - The Henry Luce Course' },
  { value: 'MATH', label: 'MATH - Mathematics' },
  { value: 'MB&B', label: 'MB&B - Molecular Biophysics & Biochem' },
  { value: 'MBIO', label: 'MBIO - Microbiology' },
  { value: 'MCDB', label: 'MCDB - Molecular, Cellular & Dev Biol' },
  { value: 'MDVL', label: 'MDVL - Medieval Studies' },
  { value: 'MED', label: 'MED - Master of Environmental Design' },
  { value: 'MEDC', label: 'MEDC - Courses in School of Medicine' },
  { value: 'MEDR', label: 'MEDR - Clinical Clerkships' },
  { value: 'MENG', label: 'MENG - Mechanical Engineering' },
  { value: 'MESO', label: 'MESO - Mesopotamia' },
  { value: 'MGMT', label: 'MGMT - Management' },
  { value: 'MGRK', label: 'MGRK - Modern Greek' },
  { value: 'MGT', label: 'MGT - School of Management' },
  { value: 'MIC', label: 'MIC - Microbiology' },
  { value: 'MMES', label: 'MMES - Modern Middle East Studies' },
  { value: 'MRES', label: "MRES - Master's Thesis Research" },
  { value: 'MTBT', label: 'MTBT - Modern Tibetan' },
  { value: 'MUS', label: 'MUS - School of Music' },
  { value: 'MUSI', label: 'MUSI - Music Department' },
  { value: 'NAVY', label: 'NAVY - Naval Science' },
  { value: 'NBIO', label: 'NBIO - Neurobiology' },
  { value: 'NELC', label: 'NELC - Near Eastern Langs & Civs' },
  { value: 'NHTL', label: 'NHTL - Nahuatl' },
  { value: 'NRLG', label: 'NRLG - Neurology' },
  { value: 'NSCI', label: 'NSCI - Neuroscience' },
  { value: 'NURS', label: 'NURS - Nursing' },
  { value: 'OBGN', label: 'OBGN - Obstetrics/Gynecology' },
  { value: 'OBIO', label: 'OBIO - Organismal Biology' },
  { value: 'OLPA', label: 'OLPA - Online Physician Assistant Pgm' },
  { value: 'OPRH', label: 'OPRH - Orthopaedics & Rehabilitation' },
  { value: 'OPRS', label: 'OPRS - Operations Research' },
  { value: 'OPVS', label: 'OPVS - Ophthalmology & Visual Science' },
  { value: 'ORMS', label: 'ORMS - Operations Res/Mgmt Science' },
  { value: 'OTTM', label: 'OTTM - Ottoman' },
  { value: 'PA', label: 'PA - Physician Associate Program' },
  { value: 'PATH', label: 'PATH - Pathology' },
  { value: 'PEDT', label: 'PEDT - Pediatrics' },
  { value: 'PERS', label: 'PERS - Persian' },
  { value: 'PHAR', label: 'PHAR - Pharmacology' },
  { value: 'PHIL', label: 'PHIL - Philosophy' },
  { value: 'PHUM', label: 'PHUM - Public Humanities' },
  { value: 'PHYS', label: 'PHYS - Physics' },
  { value: 'PIH', label: 'PIH - Program International Health' },
  { value: 'PLSC', label: 'PLSC - Political Science' },
  { value: 'PLSH', label: 'PLSH - Polish' },
  { value: 'PNJB', label: 'PNJB - Punjabi' },
  { value: 'PORT', label: 'PORT - Portuguese' },
  { value: 'PPM', label: 'PPM - Public & Private Management' },
  { value: 'PRAC', label: 'PRAC - Practicum Analysis' },
  { value: 'PSYC', label: 'PSYC - Psychology' },
  { value: 'PSYT', label: 'PSYT - Psychiatry' },
  { value: 'QUAL', label: 'QUAL - Preparing for Qualifying Exams' },
  { value: 'QUAN', label: 'QUAN - Quantitative Reasoning' },
  { value: 'REL', label: 'REL - Religion' },
  { value: 'RLST', label: 'RLST - Religious Studies' },
  { value: 'RNST', label: 'RNST - Renaissance Studies' },
  { value: 'ROMN', label: 'ROMN - Romanian' },
  { value: 'RSEE', label: 'RSEE - Russian & East Europe Studies' },
  { value: 'RUSS', label: 'RUSS - Russian' },
  { value: 'S&DS', label: 'S&DS - Statistics and Data Science' },
  { value: 'SAST', label: 'SAST - South Asian Studies' },
  { value: 'SBCR', label: 'SBCR - Serbian & Croatian' },
  { value: 'SBS', label: 'SBS - Social and Behavioral Sciences' },
  { value: 'SCAN', label: 'SCAN - Scandinavian' },
  { value: 'SCIE', label: 'SCIE - Science' },
  { value: 'SKRT', label: 'SKRT - Sanskrit' },
  { value: 'SLAV', label: 'SLAV - Slavic' },
  { value: 'SMTC', label: 'SMTC - Semitic' },
  { value: 'SNHL', label: 'SNHL - Sinhala' },
  { value: 'SOCY', label: 'SOCY - Sociology' },
  { value: 'SPAN', label: 'SPAN - Spanish' },
  { value: 'SPEC', label: 'SPEC - Special Divisional Major' },
  { value: 'SPTC', label: 'SPTC - Special Term Course' },
  { value: 'STAT', label: 'STAT - Statistics' },
  { value: 'STCY', label: 'STCY - Study of the City' },
  { value: 'STEV', label: 'STEV - Studies in the Environment' },
  { value: 'STRT', label: 'STRT - Start Program' },
  { value: 'SURG', label: 'SURG - Surgery' },
  { value: 'SWAH', label: 'SWAH - Kiswahili' },
  { value: 'TAML', label: 'TAML - Tamil' },
  { value: 'TBTN', label: 'TBTN - Tibetan' },
  { value: 'THST', label: 'THST - Theater Studies' },
  { value: 'TKSH', label: 'TKSH - Turkish' },
  { value: 'TPRP', label: 'TPRP - Teacher Preparation' },
  { value: 'TRAD', label: 'TRAD - Therapeutic Radiology' },
  { value: 'TWI', label: 'TWI - Twi' },
  { value: 'UKRN', label: 'UKRN - Ukrainian' },
  { value: 'URBN', label: 'URBN - Urban Studies' },
  { value: 'URDU', label: 'URDU - Heritage Urdu' },
  { value: 'USAF', label: 'USAF - Aerospace Studies' },
  { value: 'VAIR', label: 'VAIR - Visiting Assistant in Research' },
  { value: 'VIET', label: 'VIET - Vietnamese' },
  { value: 'WGSS', label: "WGSS - Women'sGender&SexualityStudies" },
  { value: 'WGST', label: "WGST - Women's & Gender Studies" },
  { value: 'WHIT', label: 'WHIT - Whitney Seminar' },
  { value: 'WLOF', label: 'WLOF - Wolof' },
  { value: 'WMST', label: "WMST - Women's Studies" },
  { value: 'YORU', label: 'YORU - Yoruba' },
  { value: 'YPKU', label: 'YPKU - PKU: Direct Enrollment' },
  { value: 'YSM', label: 'YSM - Yale School of Medicine' },
  { value: 'ZULU', label: 'ZULU - Zulu' },
] as const;
