version: '3'
services:
  api:
    ports:
      - '${SECURE_PORT:-3001}:${SECURE_PORT:-3001}'
      - 6499:6499
    volumes:
      - ../static:/usr/src/app/api/static
      - ../src:/usr/src/app/api/src
      - ../drizzle:/usr/src/app/api/drizzle
    environment:
      OVERWRITE_CATALOG: ${OVERWRITE_CATALOG:-'false'}
      HOT_RELOAD: ${HOT_RELOAD:-'true'}

    depends_on:
      db:
        condition: service_healthy

  graphql-engine:
    ports:
      - '127.0.0.1:8085:8080'

  redis:
    volumes:
      - ../redis/data:/data

  db:
    container_name: ${DB_HOST?db}
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD?password}
      POSTGRES_DB: ${DB_NAME?coursetable}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 0.5s
      timeout: 10s
      retries: 60
    volumes:
      - ../postgres/data:/var/lib/postgresql/data
    networks:
      - api

  # This container is only for dev! The prod container is at coursetable/infra/mysql
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@coursetable.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ../postgres/pgadmin/servers.json:/pgadmin4/servers.json
