services:
  api:
    build:
      args:
        HOT_RELOAD: 'false'
    ports:
      - '${INSECURE_PORT:-8040}:${INSECURE_PORT:-8040}'
    environment:
      NODE_ENV: production
      HOT_RELOAD: 'false'
    labels:
      traefik.enable: true
    networks:
      - traefik
      - api
      - db
      - api_services

networks:
  traefik:
    external: true
  db:
    external: true
  api_services:
    external: true
