version: '3'
services:
  api:
    ports:
      - '${INSECURE_PORT:-8040}:${INSECURE_PORT:-8040}'
    environment:
      NODE_ENV: production
      HOT_RELOAD: 'false'
    labels:
      traefik.enable: true
    networks:
      - traefik
      - mysql
      - api

  graphql-engine:
    networks:
      - ferry
      - api

networks:
  traefik:
    external: true
  ferry:
    external: true
  mysql:
    external: true
