services:
  api:
    ports:
      - '${INSECURE_PORT:-8040}:${INSECURE_PORT:-8040}'
    environment:
      NODE_ENV: production
      HOT_RELOAD: 'false'
    labels:
      traefik.enable: true
    networks:
      - traefik
      - api
      - db

  graphql-engine:
    networks:
      - db
      - api

networks:
  traefik:
    external: true
  db:
    external: true
