services:
  api:
    environment:
      NODE_ENV: production
      OVERWRITE_CATALOG: 'false'
      HOT_RELOAD: 'false'
    labels:
      traefik.enable: true
    networks:
      - traefik
      - api
      - db
      - api_services
    extra_hosts:
      - 'host.docker.internal:host-gateway'

networks:
  traefik:
    external: true
  db:
    external: true
  api_services:
    external: true
