version: '3'
services:
  api:
    labels:
      traefik.http.routers.coursetable-staging.rule: Host(`api-staging.coursetable.com`)
      traefik.http.routers.coursetable-staging.tls: true
      traefik.http.routers.coursetable-staging.tls.certResolver: ctresolver
      traefik.http.routers.coursetable-staging.middlewares: gzip-compress@file

  redis:
    volumes:
      - /home/app/redis/staging-data:/data
