services:
  api:
    ports:
      - '4096:4096'
      - '3001:3001'
    volumes:
      - ../api/static:/app/static

    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    build: ./mysql
    image: coursetable/api-mysql:latest
    command: --default-authentication-plugin=mysql_native_password --log-warnings
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD?password}
    ports:
      - '3306:3306'
    healthcheck:
      test:
        [
          'CMD',
          '/usr/local/bin/healthcheck.sh',
          '--su-mysql',
          '--connect',
          '--innodb_initialized',
        ]
      interval: 0.5s
      timeout: 10s
      retries: 60

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD?password}
    ports:
      - '8081:80'
