version: '3'
services:
  api:
    ports:
      - '${SECURE_PORT:-3001}:${SECURE_PORT:-3001}'
    volumes:
      - ./static:/usr/src/app/api/static
      - ./src:/usr/src/app/api/src
      - ./prisma:/usr/src/app/api/prisma
    environment:
      OVERWRITE_CATALOG: ${OVERWRITE_CATALOG:-'false'}
      HOT_RELOAD: ${HOT_RELOAD:-'true'}

    depends_on:
      mysql:
        condition: service_healthy

  # This container is only for dev! The prod container is at coursetable/infra/mysql
  mysql:
    build: ./mysql
    image: coursetable/mysql:latest
    container_name: ${MYSQL_HOST?mysql}
    command: --default-authentication-plugin=mysql_native_password --log-warnings
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD?password}
    ports:
      - '3306:3306'
    healthcheck:
      test:
        [
          'CMD',
          '/usr/local/bin/healthcheck.sh',
          '--su-mysql',
          '--connect',
          '--innodb_initialized',
        ]
      interval: 0.5s
      timeout: 10s
      retries: 60
    networks:
      - api

  # This container is only for dev! The prod container is at coursetable/infra/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: ${MYSQL_HOST?mysql}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD?password}
    ports:
      - '8081:80'
    networks:
      - api
