services:
  api:
    build:
      args:
        - HOT_RELOAD=false
    restart: always
    ports:
      - '${INSECURE_PORT:-8039}:${INSECURE_PORT:-8039}'
      - '${SECURE_PORT:-8038}:${SECURE_PORT:-8038}'
    expose:
      - '8039'
    volumes:
      - ../api/src:/usr/src/app/src
    environment:
      NODE_ENV: production
      HOT_RELOAD: 'false'
    labels:
      traefik.enable: true
      traefik.http.routers.coursetable.rule: Host(`api.coursetable.com`)
      traefik.http.routers.coursetable.tls: true
      traefik.http.routers.coursetable.tls.certResolver: ctresolver
      traefik.http.routers.coursetable.middlewares: gzip-compress@file
    networks:
      - traefik
      - mysql_default
      - default

  graphql-engine:
    restart: always
    networks:
      - ferry_default
      - default

networks:
  traefik:
    external: true
  ferry_default:
    external: true
  mysql_default:
    external: true
